version: "3.2"
services:
  order-config-server:
    build: ./order-config-server
    container_name: 'order-config-server'
    ports:
      - "8888:8888"
    networks:
      - local
    restart: always

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
        - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
      - local
    restart: always
    
  order-taking-service:
    build: ./order-taking-service
    container_name: 'order-taking-service'
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      - "order-config-server"
    restart: always

  order-approval-service:
    build: ./order-approval-service
    container_name: 'order-approval-service'
    ports:
      - "8090:8090"
    networks:
      - local
    depends_on:
      - "order-config-server"
    restart: always
networks:
  local:
    driver: bridge