version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - local

  order-approval-service:
    build: .
    container_name: 'order-approval-service'
    ports:
      - "8090:8090"
    networks:
      - local
networks:
  local:
    driver: bridge